name: Generate Pac-Man

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hugoalh/ghaction-git-push@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Pac-Man
        uses: muhammadmuzzammil1998/Pac-Man@v1.0
        with:
          username: Joaopedro0s
          token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Update Pac-Man animation"
          branch: output
